# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated from the _async directory.

#!/usr/bin/env python3
"""
ci-stable
AgentBay SDK - Label Management & Session Listing Example

This example demonstrates:
1. Session labels: get_labels, set_labels (label CRUD)
2. Session listing: filter by labels, pagination, pagination loop
"""

import os

from agentbay import AgentBay, CreateSessionParams


def main():
    api_key = os.getenv("AGENTBAY_API_KEY")
    if not api_key:
        print("Error: AGENTBAY_API_KEY environment variable not set")
        return

    agent_bay = AgentBay(api_key=api_key)
    test_sessions = []

    try:
        # =====================================================================
        # Step 1: Create sessions with labels
        # ===================================================================== print("\n[Step 1] Creating sessions with labels...")

        params1 = CreateSessionParams(labels={
            "project": "label-demo",
            "environment": "dev",
        })
        result1 = agent_bay.create(params1)
        if result1.success:
            session1 = result1.session
            test_sessions.append(session1)
            print(f"  Session 1: {session1.session_id} (env=dev)")

        params2 = CreateSessionParams(labels={
            "project": "label-demo",
            "environment": "staging",
        })
        result2 = agent_bay.create(params2)
        if result2.success:
            session2 = result2.session
            test_sessions.append(session2)
            print(f"  Session 2: {session2.session_id} (env=staging)")

        # =====================================================================
        # Step 2: Get labels for a session
        # ===================================================================== print("\n[Step 2] Getting labels for session 1...")
        labels_result = session1.get_labels()
        if labels_result.success:
            print(f"  Labels: {labels_result.data}")
        else:
            print(f"  Failed: {labels_result.error_message}")

        # =====================================================================
        # Step 3: Update labels for a session
        # ===================================================================== print("\n[Step 3] Updating labels for session 2...")
        set_result = session2.set_labels({
            "project": "label-demo",
            "environment": "staging",
            "status": "active",
        })
        if set_result.success:
            print("  Labels updated successfully")
            updated = session2.get_labels()
            if updated.success:
                print(f"  Updated labels: {updated.data}")
        else:
            print(f"  Failed: {set_result.error_message}")

        # =====================================================================
        # Step 4: List sessions filtered by labels
        # ===================================================================== print("\n[Step 4] Listing sessions with project=label-demo...")
        list_result = agent_bay.list(
            labels={"project": "label-demo"}, limit=100
        )
        if list_result.success:
            print(f"  Found {list_result.total_count} total, {len(list_result.session_ids)} on this page")
            for i, session in enumerate(list_result.session_ids, 1):
                sid = session["sessionId"]
                status = session["sessionStatus"]
                print(f"    {i}. {sid} ({status})")
        else:
            print(f"  Failed: {list_result.error_message}")

        # =====================================================================
        # Step 5: List sessions with multiple label filters
        # ===================================================================== print("\n[Step 5] Listing with project=label-demo AND environment=dev...")
        filtered = agent_bay.list(
            labels={"project": "label-demo", "environment": "dev"}, limit=100
        )
        if filtered.success:
            print(f"  Found {filtered.total_count} matching sessions")
            for i, session in enumerate(filtered.session_ids, 1):
                print(f"    {i}. {session['sessionId']} ({session['sessionStatus']})")
        else:
            print(f"  Failed: {filtered.error_message}")

        # =====================================================================
        # Step 6: List with pagination
        # ===================================================================== print("\n[Step 6] Listing with pagination (limit=1 per page)...")
        page1 = agent_bay.list(
            labels={"project": "label-demo"}, page=1, limit=1
        )
        if page1.success:
            print(f"  Page 1: {len(page1.session_ids)} session(s)")
            for session in page1.session_ids:
                print(f"    - {session['sessionId']}")

            if page1.next_token:
                page2 = agent_bay.list(
                    labels={"project": "label-demo"}, page=2, limit=1
                )
                if page2.success:
                    print(f"  Page 2: {len(page2.session_ids)} session(s)")
                    for session in page2.session_ids:
                        print(f"    - {session['sessionId']}")

        # =====================================================================
        # Step 7: Pagination loop - retrieve all sessions
        # ===================================================================== print("\n[Step 7] Retrieving all sessions with pagination loop...")
        all_sessions = []
        page = 1
        limit = 2

        while True:
            result = agent_bay.list(
                labels={"project": "label-demo"}, page=page, limit=limit
            )
            if not result.success:
                print(f"  Error on page {page}: {result.error_message}")
                break

            all_sessions.extend(result.session_ids)
            print(f"  Page {page}: {len(result.session_ids)} session(s)")

            if not result.next_token:
                break
            page += 1

        print(f"  Total retrieved: {len(all_sessions)} sessions across {page} page(s)")

        print("\n=== Label Management & Session Listing Example Completed ===")

    finally:
        # Cleanup
        print("\n[Cleanup] Deleting test sessions...")
        for session in test_sessions:
            try:
                agent_bay.delete(session)
                print(f"  Deleted: {session.session_id}")
            except Exception as e:
                print(f"  Failed to delete {session.session_id}: {e}")


if __name__ == "__main__":
    main()

