# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for different session images.
ci-stable
"""

import pytest

from agentbay import AgentBay
from agentbay import CreateSessionParams


@pytest.mark.sync
def test_ubuntu_session(agent_bay_client: AgentBay):
    """Test creating Ubuntu session."""
    params = CreateSessionParams(image_id="linux_latest")
    result = agent_bay_client.create(params)
    assert result.success

    session = result.session
    print(f"Ubuntu session created: {session.session_id}")

    # Test basic command
    cmd_result = session.command.execute_command("uname -a")
    assert cmd_result.success
    print(f"OS info: {cmd_result.output[:50]}...")

    session.delete()


@pytest.mark.sync
def test_browser_session(agent_bay_client: AgentBay):
    """Test creating browser session."""
    params = CreateSessionParams(image_id="browser_latest")
    result = agent_bay_client.create(params)
    assert result.success

    session = result.session
    print(f"Browser session created: {session.session_id}")

    session.delete()
