# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for AgentBay async client and session operations."""

import time

from agentbay import (
    BWList,
    DeletePolicy,
    DownloadPolicy,
    ExtractPolicy,
    Lifecycle,
    RecyclePolicy,
    SyncPolicy,
    UploadPolicy,
    WhiteList,
)

# make_session factory fixture is provided by conftest.py (auto-loaded by pytest)


# ---------------------------------------------------------------------------
# TestAgentBay – create / delete
# ---------------------------------------------------------------------------


def test_create_list_delete(make_session):
    """Test create and delete methods."""
    print("Creating a new session...")
    lc = make_session("linux_latest")

    s = lc._result.session
    print(f"Session created with ID: {s.session_id}")
    assert s.session_id is not None
    assert s.session_id != ""
    # Session cleanup is handled by the make_session factory in conftest.py


# ---------------------------------------------------------------------------
# TestSession – properties and basic operations
# ---------------------------------------------------------------------------


def test_session_properties(make_session):
    """Test session properties and methods."""
    lc = make_session("linux_latest")
    s = lc._result.session
    assert s.session_id is not None
    assert s.session_id != ""


def test_command(make_session):
    """Test command execution."""
    lc = make_session("linux_latest")
    s = lc._result.session
    if s.command:
        print("Executing command...")
        try:
            response = s.command.execute_command("ls")
            print(f"Command execution result: {response}")
            assert response is not None
            assert response.success, f"Command failed: {response.error_message}"
            assert "tool not found" not in response.output.lower(), \
                "Command.execute_command returned 'tool not found'"
        except Exception as e:
            print(f"Note: Command execution failed: {e}")
    else:
        print("Note: Command interface is None, skipping command test")


def test_filesystem(make_session):
    """Test filesystem operations."""
    lc = make_session("linux_latest")
    s = lc._result.session
    if s.file_system:
        print("Reading file...")
        try:
            result = s.file_system.read_file("/etc/hosts")
            print(f"ReadFile result: content='{result}'")
            assert result is not None
            assert result.success, f"Read file failed: {result.error_message}"
            assert "tool not found" not in result.content.lower(), \
                "FileSystem.read_file returned 'tool not found'"
            print("File read successful")
        except Exception as e:
            print(f"Note: File operation failed: {e}")
    else:
        print("Note: FileSystem interface is None, skipping file test")


# ---------------------------------------------------------------------------
# RecyclePolicy – session creation (network)
# ---------------------------------------------------------------------------


def test_create_session_with_custom_recycle_policy(make_session):
    """Test creating session with custom recyclePolicy using Lifecycle_1Day."""
    recycle_policy = RecyclePolicy(lifecycle=Lifecycle.LIFECYCLE_1DAY, paths=[""])
    custom_sync_policy = SyncPolicy(
        upload_policy=UploadPolicy.default(),
        download_policy=DownloadPolicy.default(),
        delete_policy=DeletePolicy.default(),
        extract_policy=ExtractPolicy.default(),
        recycle_policy=recycle_policy,
        bw_list=BWList(white_lists=[WhiteList(path="", exclude_paths=[])]),
    )

    lc = make_session(
        "linux_latest",
        context_name="test-recycle-context",
        context_path="/test/recycle/path",
        context_policy=custom_sync_policy,
    )
    s = lc._result.session
    assert s is not None
    assert s.session_id is not None
    assert len(s.session_id) > 0
    print(f"Session created successfully with ID: {s.session_id}")


# ---------------------------------------------------------------------------
# WhiteList pattern (BWList is_path_regex + is_exclude_regex)
# ---------------------------------------------------------------------------


def _collect_all_files(agent_bay, context_id: str, folder_path: str, sep: str = "\\") -> list:
    """Recursively collect only FILE entries under folder_path.

    Works for both Windows-style (sep="\\") and Linux-style (sep="/") paths.
    list_files accepts the local path and returns entries whose file_path is an OSS-style path.
    For FOLDER entries: extract the last segment from entry.file_path and
      build the next local path = folder_path + sep + last_segment, then recurse.
    For FILE entries: extract the last segment (file name) and store it.
    Returns a flat list of file name strings collected under folder_path.
    """
    result = agent_bay.context.list_files(
        context_id=context_id,
        parent_folder_path=folder_path,
        page_size=200,
    )
    if not result.success or not result.entries:
        return []
    file_paths = []
    for entry in result.entries:
        ftype = (entry.file_type or "").upper()
        # Extract the last segment from the OSS path
        last_segment = entry.file_path.rstrip("/").rsplit("/", 1)[-1]
        if ftype in ("FOLDER", "DIR", "DIRECTORY"):
            # Build local sub-path and recurse
            sub_path = folder_path.rstrip(sep) + sep + last_segment
            file_paths.extend(
                _collect_all_files(agent_bay, context_id, sub_path, sep=sep)
            )
        else:
            # FILE: store the file name
            file_paths.append(last_segment)
    return file_paths


def _make_bwlist_sync_policy() -> SyncPolicy:
    """Build a SyncPolicy with BWList: include 'project-.*' dirs, exclude 'cache.*' sub-dirs."""
    return SyncPolicy(
        upload_policy=UploadPolicy.default(),
        download_policy=DownloadPolicy.default(),
        delete_policy=DeletePolicy.default(),
        extract_policy=ExtractPolicy.default(),
        recycle_policy=RecyclePolicy.default(),
        bw_list=BWList(white_lists=[
            WhiteList(
                path=r"project-.*",
                is_path_regex=True,
                exclude_paths=[r"cache.*"],
                is_exclude_regex=True,
            )
        ]),
    )


def _verify_bwlist_oss_files(agent_bay, context_id: str, base: str, sep: str = "\\") -> None:
    """Verify OSS file list after a BWList-filtered upload.

    Asserts:
      - Exactly 3 files uploaded (main.py, README.txt, config.json)
      - temp.log is absent (excluded by BWList)
    """
    print("\n=== Verifying OSS content via context.list_files ===")
    probe = agent_bay.context.list_files(
        context_id=context_id, parent_folder_path=base, page_size=200
    )
    entry_count = len(probe.entries) if probe.entries else 0
    print(f"  list_files({base!r}) -> success={probe.success}, entries={entry_count}")

    all_files: list = []
    if probe.entries:
        for e in probe.entries:
            ftype = (e.file_type or "").upper()
            last_segment = e.file_path.rstrip("/").rsplit("/", 1)[-1]
            print(f"    [{ftype}] {e.file_path!r}  -> last_segment={last_segment!r}")
            if ftype in ("FOLDER", "DIR", "DIRECTORY"):
                sub_path = base.rstrip(sep) + sep + last_segment
                print(f"      Recursing into {sub_path!r}...")
                sub_files = _collect_all_files(agent_bay, context_id, sub_path, sep=sep)
                all_files.extend(sub_files)
            else:
                all_files.append(e.file_path)
    else:
        print("  WARNING: No entries found in OSS.")

    print(f"  Collected {len(all_files)} file(s) total")
    print(f"\n  === All files in OSS ({len(all_files)} total) ===")
    assert len(all_files) == 3, f"Expected 3 files in OSS, got {len(all_files)}: {all_files}"
    for p in all_files:
        print(f"    {p}")

    for name in ["main.py", "README.txt", "config.json"]:
        found = any(name in p for p in all_files)
        print(f"  {'FOUND' if found else 'NOT FOUND'}: {name}")
        assert found, f"Expected '{name}' in OSS after BWList upload filter, not found in: {all_files}"
    print("\u2705 Expected files present in OSS")

    for name in ["temp.log"]:
        found = any(name in p for p in all_files)
        print(f"  {'FOUND (should be absent!)' if found else 'correctly absent'}: {name}")
        assert not found, f"Expected '{name}' ABSENT (excluded by BWList), but found in: {all_files}"
    print("\u2705 Excluded files correctly absent from OSS")


def test_create_session_with_pattern_bwlist_windows(make_session):
    """Test ContextSync BWList with is_path_regex=True and is_exclude_regex=True.

    Single-session strategy:
      1. Create session WITH BWList configured (upload filter).
      2. Write test files onto the session's local FS.
      3. delete(sync_context=True) triggers upload; BWList filters which files go to OSS.
      4. Poll context.list_files(base) to find OSS entries.
      5. Recursively collect all FILE entries from OSS root.
      6. Assert expected files present, excluded files absent.

    File structure:
        testdata/project-alpha/main.py
        testdata/project-alpha/README.txt
        testdata/project-beta/config.json
        testdata/project-beta/cache/temp.log  <- excluded by exclude_paths regex

    BWList (upload filter):
        path=r"project-.*"  (is_path_regex=True)
        exclude_paths=[r"cache.*"]  (is_exclude_regex=True)

    Expected in OSS:
        PRESENT:  project-alpha/main.py, project-alpha/README.txt, project-beta/config.json
        ABSENT:   project-beta/cache/temp.log
    """
    print("Testing BWList is_path_regex + is_exclude_regex via single-session strategy...")

    base = "C:\\Users\\Administrator\\testdata"
    context_name = f"bwlist-ctx-{int(time.time())}"

    sync_policy = SyncPolicy(
        upload_policy=UploadPolicy.default(),
        download_policy=DownloadPolicy.default(),
        delete_policy=DeletePolicy.default(),
        extract_policy=ExtractPolicy.default(),
        recycle_policy=RecyclePolicy.default(),
        bw_list=BWList(white_lists=[
            WhiteList(
                path=r"project-.*",
                is_path_regex=True,
                exclude_paths=[r"cache.*"],
                is_exclude_regex=True,
            )
        ]),
    )

    # ── Create session WITH BWList ─────────────────────────────────────────────
    lc = make_session(
        "computer-use-ubuntu-2204",
        context_name=context_name,
        context_path=base,
        context_policy=sync_policy,
    )
    s = lc._result.session
    agent_bay = lc.agent_bay
    context_id = lc._owned_contexts[0].id
    print(f"Session ID: {s.session_id}, Context ID: {context_id}")

    # ── Write test files onto local FS ────────────────────────────────────────
    fs = s.file_system
    for d in [base, f"{base}\\project-alpha", f"{base}\\project-beta", f"{base}\\project-beta\\cache"]:
        r = fs.create_directory(d)
        print(f"  mkdir {d}: {'OK' if r.success else r.error_message}")

    test_files = [
        (f"{base}\\project-alpha\\main.py",       "# main entry point\nprint('hello')\n"),
        (f"{base}\\project-alpha\\README.txt",     "Project Alpha README\n"),
        (f"{base}\\project-beta\\config.json",     '{"env": "test"}\n'),
        (f"{base}\\project-beta\\cache\\temp.log", "temporary log\n"),
    ]
    for fpath, content in test_files:
        r = fs.write_file(fpath, content)
        print(f"  write {fpath}: {'OK' if r.success else r.error_message}")

    # ── delete via lifecycle (sync_context=True is set automatically) ──────────
    print("  Deleting session with sync_context=True (BWList upload filter applied)...")
    del_result = lc.delete()
    assert del_result.success, f"Session delete failed: {del_result.error_message}"
    print("  Session deleted. Filtered upload triggered.")

    # ── Verify OSS content ──────────────────────────────────────────────────
    _verify_bwlist_oss_files(agent_bay, context_id, base, sep="\\")
    print("BWList with is_path_regex + is_exclude_regex verified successfully (Windows)")


def test_create_session_with_pattern_bwlist_linux(make_session):
    """Test ContextSync BWList with is_path_regex=True and is_exclude_regex=True (Linux path).

    Same BWList strategy as the Windows counterpart, but runs on a Linux session
    with paths under /home/wuying/testdata.

    File structure:
        /home/wuying/testdata/project-alpha/main.py
        /home/wuying/testdata/project-alpha/README.txt
        /home/wuying/testdata/project-beta/config.json
        /home/wuying/testdata/project-beta/cache/temp.log  <- excluded by exclude_paths regex

    BWList (upload filter):
        path=r"project-.*"  (is_path_regex=True)
        exclude_paths=[r"cache.*"]  (is_exclude_regex=True)

    Expected in OSS:
        PRESENT:  project-alpha/main.py, project-alpha/README.txt, project-beta/config.json
        ABSENT:   project-beta/cache/temp.log
    """
    print("Testing BWList is_path_regex + is_exclude_regex via single-session strategy (Linux)...")

    base = "/home/wuying/testdata"
    context_name = f"bwlist-linux-ctx-{int(time.time())}"

    # ── Create session WITH BWList ─────────────────────────────────────────────
    lc = make_session(
        "linux_latest",
        context_name=context_name,
        context_path=base,
        context_policy=_make_bwlist_sync_policy(),
    )
    s = lc._result.session
    agent_bay = lc.agent_bay
    context_id = lc._owned_contexts[0].id
    print(f"Session ID: {s.session_id}, Context ID: {context_id}")

    # ── Write test files onto local FS ────────────────────────────────────────
    fs = s.file_system
    for d in [base, f"{base}/project-alpha", f"{base}/project-beta", f"{base}/project-beta/cache"]:
        r = fs.create_directory(d)
        print(f"  mkdir {d}: {'OK' if r.success else r.error_message}")

    test_files = [
        (f"{base}/project-alpha/main.py",       "# main entry point\nprint('hello')\n"),
        (f"{base}/project-alpha/README.txt",     "Project Alpha README\n"),
        (f"{base}/project-beta/config.json",     '{"env": "test"}\n'),
        (f"{base}/project-beta/cache/temp.log", "temporary log\n"),
    ]
    for fpath, content in test_files:
        r = fs.write_file(fpath, content)
        print(f"  write {fpath}: {'OK' if r.success else r.error_message}")

    # ── delete via lifecycle (sync_context=True is set automatically) ──────────
    print("  Deleting session with sync_context=True (BWList upload filter applied)...")
    del_result = lc.delete()
    assert del_result.success, f"Session delete failed: {del_result.error_message}"
    print("  Session deleted. Filtered upload triggered.")

    # ── Verify OSS content ──────────────────────────────────────────────────
    _verify_bwlist_oss_files(agent_bay, context_id, base, sep="/")
    print("BWList with is_path_regex + is_exclude_regex verified successfully (Linux)")



# ---------------------------------------------------------------------------
# BrowserContext – session creation (network)
# ---------------------------------------------------------------------------


def test_create_session_with_browser_context_default_recycle_policy(make_session):
    """Test creating session with BrowserContext using default RecyclePolicy."""
    print("Testing session creation with BrowserContext (default RecyclePolicy)...")

    context_name = f"test-browser-context-default-{int(time.time())}"
    lc = make_session(
        "linux_latest",
        browser_name=context_name,
        browser_kwargs={"auto_upload": True},
    )
    s = lc._result.session
    assert s is not None
    assert s.session_id is not None
    assert len(s.session_id) > 0
    print(f"Session created successfully with ID: {s.session_id}")
    print(
        "Session with BrowserContext (default RecyclePolicy) created and verified successfully"
    )
    # Session and browser context cleanup is handled by the make_session factory in conftest.py


# ---------------------------------------------------------------------------
# Session pause / resume
# ---------------------------------------------------------------------------


def test_session_pause_and_resume(make_session):
    """Test pausing and resuming a session."""
    lc = make_session("linux_latest")
    s = lc._result.session
    print(f"Session created with ID: {s.session_id}")

    # Pause
    print("\n=== Testing session pause ===")
    pause_result = s.beta_pause(timeout=300, poll_interval=2)
    print(f"Pause result - Success: {pause_result.success}, Status: {pause_result.status}")
    assert pause_result.success, f"Session pause failed: {pause_result.error_message}"
    status = lc.get_status()
    assert status == "PAUSED", f"Expected status PAUSED, got {status}"
    print("Session paused successfully")

    # Resume
    print("\n=== Testing session resume ===")
    resume_result = s.beta_resume(timeout=300, poll_interval=2)
    print(f"Resume result - Success: {resume_result.success}, Status: {resume_result.status}")
    assert resume_result.success, f"Session resume failed: {resume_result.error_message}"
    assert resume_result.status == "RUNNING", \
        f"Expected status RUNNING, got {resume_result.status}"
    print("Session resumed successfully")

    print("\n=== Pause/Resume test completed successfully ===")

