import time
# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

import asyncio
import os
import pytest

pytestmark = [pytest.mark.asyncio, pytest.mark.integration]

IMAGE_ID = "linux_latest"


@pytest.fixture(scope="module")
def event_loop():
    loop = asyncio.new_event_loop()
    yield loop



@pytest.fixture(scope="module")
def agent_bay():
    api_key = os.environ.get("AGENTBAY_API_KEY")
    if not api_key:
        pytest.skip("AGENTBAY_API_KEY not set")
    from agentbay import AgentBay
    return AgentBay()


@pytest.fixture
def pty_session(agent_bay):
    from agentbay import CreateSessionParams
    result = agent_bay.create(CreateSessionParams(image_id=IMAGE_ID))
    assert result.success, f"Failed to create session: {result}"
    session = result.session
    yield session
    try:
        session.delete()
    except Exception as e:
        print(f"Warning: failed to delete session: {e}")


class TestPtyCreateAndEcho:
    def test_create_and_echo(self, pty_session):
        """Create PTY, run echo, verify output."""
        output_chunks = []

        def on_data(data: bytes):
            output_chunks.append(data)

        handle = pty_session.pty.create(on_data=on_data)
        assert handle.pty_session_id
        assert handle.is_connected

        time.sleep(1)

        handle.send_input(b"echo 'PTY_TEST_OK_98765'\r")
        time.sleep(2)

        combined = b"".join(output_chunks).decode("utf-8", errors="replace")
        assert "PTY_TEST_OK_98765" in combined

        handle.disconnect()


class TestPtyCtrlC:
    def test_ctrl_c(self, pty_session):
        """Send Ctrl+C to interrupt a running command."""
        output_chunks = []

        def on_data(data: bytes):
            output_chunks.append(data)

        handle = pty_session.pty.create(on_data=on_data)
        time.sleep(1)

        handle.send_input(b"sleep 100\r")
        time.sleep(1)

        handle.send_input(b"\x03")
        time.sleep(2)

        combined = b"".join(output_chunks).decode("utf-8", errors="replace")
        assert "^C" in combined or "$" in combined

        handle.disconnect()


class TestPtyResize:
    def test_resize(self, pty_session):
        """Resize terminal to 120x40."""
        handle = pty_session.pty.create()
        time.sleep(1)

        handle.resize(120, 40)
        time.sleep(1)

        handle.disconnect()


class TestPtyList:
    def test_list(self, pty_session):
        """List should include the created PTY."""
        handle = pty_session.pty.create()
        time.sleep(1)

        sessions = pty_session.pty.list()
        ids = [s.pty_session_id for s in sessions]
        assert handle.pty_session_id in ids

        handle.disconnect()


class TestPtyConnect:
    def test_disconnect_and_reconnect(self, pty_session):
        """Disconnect then reconnect, verify I/O works."""
        output1 = []
        handle1 = pty_session.pty.create(
            on_data=lambda d: output1.append(d)
        )
        time.sleep(1)

        handle1.send_input(b"echo 'BEFORE_DISCONNECT'\r")
        time.sleep(1)

        pty_id = handle1.pty_session_id
        handle1.disconnect()
        assert not handle1.is_connected

        output2 = []
        handle2 = pty_session.pty.connect(
            pty_id, on_data=lambda d: output2.append(d)
        )
        assert handle2.is_connected

        handle2.send_input(b"echo 'AFTER_RECONNECT'\r")
        time.sleep(2)

        combined = b"".join(output2).decode("utf-8", errors="replace")
        assert "AFTER_RECONNECT" in combined

        handle2.disconnect()


class TestPtyExit:
    def test_exit_event(self, pty_session):
        """Send exit, verify pty.exit event and wait() returns exit code 0."""
        handle = pty_session.pty.create()
        time.sleep(1)

        handle.send_input(b"exit\r")
        exit_code = handle.wait(timeout_s=10)
        assert exit_code == 0
        assert handle.exit_code == 0
        assert not handle.is_connected


class TestPtyKill:
    def test_kill(self, pty_session):
        """Kill PTY and verify exit code is -9."""
        handle = pty_session.pty.create()
        time.sleep(1)

        handle.kill()
        exit_code = handle.wait(timeout_s=10)
        assert exit_code == -9


class TestPtyMultiple:
    def test_multiple_ptys(self, pty_session):
        """Create 2 PTYs, each works independently."""
        output1 = []
        output2 = []
        handle1 = pty_session.pty.create(
            on_data=lambda d: output1.append(d)
        )
        handle2 = pty_session.pty.create(
            on_data=lambda d: output2.append(d)
        )
        time.sleep(1)

        handle1.send_input(b"echo 'FROM_PTY_1'\r")
        handle2.send_input(b"echo 'FROM_PTY_2'\r")
        time.sleep(2)

        combined1 = b"".join(output1).decode("utf-8", errors="replace")
        combined2 = b"".join(output2).decode("utf-8", errors="replace")
        assert "FROM_PTY_1" in combined1
        assert "FROM_PTY_2" in combined2

        handle1.disconnect()
        handle2.disconnect()


class TestPtyDisconnectError:
    def test_send_input_after_disconnect_raises(self, pty_session):
        """Send input after disconnect should raise PtyNotConnectedError."""
        from agentbay import PtyNotConnectedError

        handle = pty_session.pty.create()
        time.sleep(1)

        handle.disconnect()
        assert not handle.is_connected

        with pytest.raises(PtyNotConnectedError):
            handle.send_input(b"should fail\r")


class TestPtyResizeVerify:
    def test_resize_columns_lines(self, pty_session):
        """Resize terminal and verify COLUMNS/LINES via tput."""
        output_chunks = []

        def on_data(data: bytes):
            output_chunks.append(data)

        handle = pty_session.pty.create(
            cols=80, rows=24, on_data=on_data
        )
        time.sleep(1)

        handle.resize(150, 50)
        time.sleep(1)

        handle.send_input(b"tput cols; tput lines\r")
        time.sleep(2)

        combined = b"".join(output_chunks).decode("utf-8", errors="replace")
        assert "150" in combined
        assert "50" in combined

        handle.disconnect()
