# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""
Integration tests for watch_directory functionality.
"""

import threading
import time

import pytest

from agentbay import CreateSessionParams


def _wait_ready(ready_event: threading.Event, timeout: float = 30):
    """Wait for a threading.Event without blocking the asyncio event loop."""
    deadline = time.monotonic() + timeout
    while not ready_event.is_set():
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError("ready_event was not set within timeout")
        time.sleep(0.05)


@pytest.mark.sync
def test_watch_directory(make_session):
    """
    Test the watch_directory functionality by:
    1. Creating a session with linux_latest ImageId
    2. Setting up directory monitoring with a callback
    3. Creating and modifying files
    4. Verifying that callbacks are triggered with correct events
    5. Testing deduplication of events
    """
    print("=== Testing watch_directory functionality ===\n")

    lc = make_session(params=CreateSessionParams(image_id="linux_latest"))
    session = lc._result.session
    print(f"Session created successfully with ID: {session.session_id}")

    detected_events = []
    callback_calls = []

    def file_change_callback(events):
        """Callback function to handle detected file changes."""
        callback_calls.append(len(events))
        detected_events.extend(events)
        print(f"\nCallback triggered with {len(events)} events:")
        for event in events:
            print(f"   - {event.event_type}: {event.path} ({event.path_type})")

    # Use a unique directory name to avoid stale state from previous runs
    test_dir = f"/tmp/watch_test_{int(time.time())}"
    print(f"\n1. Creating test directory: {test_dir}")
    create_dir_result = session.file_system.create_directory(test_dir)
    assert create_dir_result.success, f"Failed to create directory: {create_dir_result.error_message}"

    test_file1 = f"{test_dir}/test_file.txt"

    print("\n2. Starting directory monitoring...")
    monitor_thread = session.file_system.watch_directory(
        path=test_dir,
        callback=file_change_callback,
        interval=0.5,
    )
    monitor_thread.start()
    _wait_ready(monitor_thread.ready_event)
    time.sleep(1)
    print("Directory monitoring started (baseline established)")

    try:
        print("\n3. Creating a new file...")
        write_result = session.file_system.write_file(test_file1, "Hello, World!")
        assert write_result.success, f"Failed to write file: {write_result.error_message}"
        time.sleep(3)

        print("\n4. Modifying the file...")
        modify_result = session.file_system.write_file(test_file1, "Modified content")
        assert modify_result.success, f"Failed to modify file: {modify_result.error_message}"
        time.sleep(3)

    finally:
        print("\n5. Stopping directory monitoring...")
        monitor_thread.stop_event.set()
        monitor_thread.join(timeout=5)
        print("Directory monitoring stopped")

    print(f"\n=== RESULTS ===")
    print(f"Total callback calls: {len(callback_calls)}")
    print(f"Total events detected: {len(detected_events)}")
    print("\nDetected events:")
    for i, event in enumerate(detected_events, 1):
        print(f"  {i}. {event}")

    # write_file to non-existent file: create + modify = 2 events
    # write_file to existing file:     modify = 1 event
    # Total = 3
    expected_events = 3
    assert len(detected_events) == expected_events, (
        f"Expected exactly {expected_events} events, got {len(detected_events)}\n"
        "Breakdown: test_file.txt new(2) + modify(1) = 3"
    )
    print(f"Captured expected number of events: {len(detected_events)}")

    create_events = sum(1 for e in detected_events if e.event_type == "create")
    modify_events = sum(1 for e in detected_events if e.event_type == "modify")
    print(f"\nEvent type breakdown:")
    print(f"  Create events: {create_events} (expected: 1)")
    print(f"  Modify events: {modify_events} (expected: 2)")
    assert create_events == 1, f"Expected 1 create events, got {create_events}"
    assert modify_events == 2, f"Expected 2 modify events, got {modify_events}"
    print("Event type distribution is correct")

    event_keys = set()
    duplicates = 0
    for event in detected_events:
        key = (event.event_type, event.path, event.path_type)
        if key in event_keys:
            duplicates += 1
        else:
            event_keys.add(key)
    assert duplicates == 0, f"Expected 0 duplicate events, got {duplicates}"
    print("Event deduplication is working correctly")

    print("\nwatch_directory test completed successfully!")


@pytest.mark.sync
def test_watch_directory_no_events_after_stop(make_session):
    """
    Negative test: after stopping the watch, new file operations
    must NOT trigger callbacks.

    Steps:
    1. Create session and test directory
    2. Start watching and wait for baseline
    3. Create a file and verify events are detected
    4. Stop watching
    5. Create another file AFTER stop
    6. Wait, then verify no new events were received
    """
    print("=== Testing no events after stop ===\n")

    lc = make_session(params=CreateSessionParams(image_id="linux_latest"))
    session = lc._result.session
    print(f"Session created with ID: {session.session_id}")

    detected_events = []

    def file_change_callback(events):
        detected_events.extend(events)
        print(f"Callback triggered with {len(events)} events")

    test_dir = f"/tmp/watch_stop_test_{int(time.time())}"

    create_result = session.file_system.create_directory(test_dir)
    assert create_result.success, f"Failed to create directory: {create_result.error_message}"
    print(f"Test directory created: {test_dir}")

    print("\n1. Starting directory monitoring...")
    monitor_thread = session.file_system.watch_directory(
        path=test_dir,
        callback=file_change_callback,
        interval=0.5,
    )
    monitor_thread.start()
    _wait_ready(monitor_thread.ready_event)
    time.sleep(1)
    print("Monitoring started")

    print("\n2. Creating a file (should trigger events)...")
    session.file_system.write_file(f"{test_dir}/before_stop.txt", "before stop")
    time.sleep(5)

    events_before_stop = len(detected_events)
    print(f"Events before stop: {events_before_stop}")
    assert events_before_stop > 0, "Should detect at least 1 event before stop"
    print("Events detected before stop")

    print("\n3. Stopping directory monitoring...")
    monitor_thread.stop_event.set()
    monitor_thread.join(timeout=10)
    print("Monitoring stopped")

    print("\n4. Creating a file AFTER stop (should NOT trigger events)...")
    session.file_system.write_file(f"{test_dir}/after_stop.txt", "after stop")
    time.sleep(3)

    events_after_stop = len(detected_events)
    new_events = events_after_stop - events_before_stop
    print(f"New events after stop: {new_events}")

    assert new_events == 0, f"Expected 0 new events after stop, got {new_events}"
    print("No events after stop - negative verification passed!")

    print("\n=== No events after stop test completed ===")
