# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for concurrent session operations.
ci-stable
"""


import pytest

from agentbay import AgentBay


@pytest.mark.sync
def test_concurrent_file_operations(agent_bay_client: AgentBay):
    """Test concurrent file operations in same session."""
    result = agent_bay_client.create()
    assert result.success
    session = result.session

    fs = session.file_system

    # Concurrent writes
    tasks = [
        fs.write_file(f"/tmp/concurrent_{i}.txt", f"content_{i}") for i in range(5)
    ]
    results = [task for task in tasks]

    assert all(r.success for r in results)
    print("Concurrent file operations successful")

    session.delete()


@pytest.mark.sync
def test_concurrent_commands(agent_bay_client: AgentBay):
    """Test concurrent command execution."""
    result = agent_bay_client.create()
    assert result.success
    session = result.session

    cmd = session.command

    # Concurrent commands
    tasks = [cmd.execute_command(f"echo 'test_{i}'") for i in range(3)]
    results = [task for task in tasks]

    assert all(r.success for r in results)
    print("Concurrent commands executed successfully")

    session.delete()
