# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for command pipes and redirects."""
# ci-stable

import pytest


@pytest.fixture
def test_session(make_session):
    lc = make_session()
    return lc._result.session


@pytest.mark.sync
def test_command_pipe(test_session):
    """Test command with pipe."""
    cmd = test_session.command
    result = cmd.execute_command("echo 'hello world' | grep 'hello'")
    assert result.success
    assert "hello" in result.output
    print("Command with pipe executed successfully")


@pytest.mark.sync
def test_command_redirect(test_session):
    """Test command with redirect."""
    cmd = test_session.command
    fs = test_session.file_system

    # Write to file using redirect
    result = cmd.execute_command("echo 'test content' > /tmp/redirect_test.txt")
    assert result.success

    # Read file to verify
    read_result = fs.read_file("/tmp/redirect_test.txt")
    assert read_result.success
    assert "test content" in read_result.content
    print("Command with redirect executed successfully")


@pytest.mark.sync
def test_command_append(test_session):
    """Test command with append redirect."""
    cmd = test_session.command
    fs = test_session.file_system

    # Write initial content
    cmd.execute_command("echo 'line1' > /tmp/append_test.txt")

    # Append content
    result = cmd.execute_command("echo 'line2' >> /tmp/append_test.txt")
    assert result.success

    # Read file to verify
    read_result = fs.read_file("/tmp/append_test.txt")
    assert read_result.success
    assert "line1" in read_result.content
    assert "line2" in read_result.content
    print("Command with append executed successfully")
