import time
# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for Computer window management functionality."""

# ci-stable
import aiohttp
from pathlib import Path

import pytest

from agentbay import CreateSessionParams


@pytest.fixture
def session(make_session):
    """Create a session with windows_latest image.

    Note: Computer module requires a desktop environment.
    Uses windows_latest (computer use image with Windows desktop).
    """
    lc = make_session(params=CreateSessionParams(image_id="windows_latest"))
    return lc._result.session


def save_screenshot_from_url(screenshot_url: str, filename: str) -> None:
    """Download screenshot from URL and save as PNG file in python/screenshots directory."""
    # Get the current file's directory and navigate to python root
    current_dir = Path(__file__).parent
    python_root = current_dir.parent.parent.parent  # Go up from tests/integration/_async to python root
    screenshots_dir = python_root / "screenshots"

    # Create screenshots directory if it doesn't exist
    screenshots_dir.mkdir(exist_ok=True)

    print(f"DEBUG: Downloading screenshot from URL: {screenshot_url}")

    # Download the screenshot from URL using aiohttp
    with aiohttp.ClientSession() as session:
        with session.get(screenshot_url) as response:
            response.raise_for_status()
            image_data = response.read()

    # Validate that we have some image data
    if len(image_data) == 0:
        raise ValueError("Downloaded image data is empty")

    print(f"DEBUG: Downloaded image data length: {len(image_data)} bytes")

    # Write to file
    file_path = screenshots_dir / filename
    with open(file_path, 'wb') as f:
        f.write(image_data)

    print(f"DEBUG: Successfully saved screenshot to {file_path}")


@pytest.mark.sync
def test_window_management_lifecycle(session):
    """Test complete window management lifecycle with Calculator."""
    print("\nTest: Window Management Lifecycle...")

    # Start Calculator app
    print("Starting Calculator app...")
    installed_apps_result = session.computer.get_installed_apps()
    if installed_apps_result.success and len(installed_apps_result.data) > 0:
        print(f"  ✅ Found {len(installed_apps_result.data)} installed applications")

        # Find a suitable app to work with (prefer Calculator, fallback to first app)
        target_app = None
        for app in installed_apps_result.data:
            if hasattr(app, 'name') and ("calculator" in app.name.lower() or "计算器" in app.name.lower()):
                target_app = app
                print(f"  🎯 Selected Calculator for demonstration")
                break

        if target_app is None:
            target_app = installed_apps_result.data[0]
            app_name = getattr(target_app, 'name', 'Unknown App')
            print(f"  🎯 Selected {app_name} for demonstration")

        start_cmd = target_app.start_cmd
        print(f"  Starting start_cmd {start_cmd}...")
        app_name = getattr(target_app, 'name', 'Unknown App')
    else:
        pytest.fail(f"Failed to get installed apps: {installed_apps_result.error_message}")
    assert installed_apps_result.success, f"Failed to start Calculator: {installed_apps_result.error_message}"
    assert len(installed_apps_result.data) > 0, "No processes returned"

    # Wait for app to be fully loaded
    time.sleep(3)

    # Start the application
    print(f"  Starting {app_name}...")
    app_pname = None
    start_result = session.computer.start_app(start_cmd)
    if start_result.success and len(start_result.data) > 0:
        print(f"  ✅ Application started successfully")

        # Get process information for cleanup
        first_process = start_result.data[0]
        app_pname = getattr(first_process, 'pname', None)

        # Wait for app to fully start
        time.sleep(3)
    else:
        pytest.fail(f"Failed to start application: {start_result.error_message}")
    calculator_window_id = None

    # Test ListRootWindows
    print("Testing list_root_windows...")
    windows_result = session.computer.list_root_windows()
    assert windows_result.success, f"List root windows failed: {windows_result.error_message}"
    assert windows_result.windows is not None, "Windows list should not be None"
    assert isinstance(windows_result.windows, list), "Windows should be a list"

    # Find Calculator window
    for window in windows_result.windows:
        print(f"Found window: {window.title} (ID: {window.window_id})")

    target_window = windows_result.windows[0]
    calculator_window_id = target_window.window_id
    window_title = target_window.title
    print(f"  🎯 Selected window: ID={calculator_window_id}, Title='{window_title}'")

    assert calculator_window_id is not None, "Calculator window should be found in root windows list"
    assert calculator_window_id > 0, "Calculator window ID should be valid"

    # Test ActivateWindow
    print("Testing activate_window...")
    activate_result = session.computer.activate_window(calculator_window_id)
    assert activate_result.success, f"Activate window failed: {activate_result.error_message}"
    print(f"Successfully activated Calculator window (ID: {calculator_window_id})")
    time.sleep(1)

    # Test GetActiveWindow
    print("Testing get_active_window...")
    active_result = session.computer.get_active_window()
    assert active_result.success, f"Get active window failed: {active_result.error_message}"
    assert active_result.window is not None, "Active window should not be None"

    if active_result.window:
        print(f"Active window: {active_result.window.title} (ID: {active_result.window.window_id})({calculator_window_id})")

    # Test FocusMode
    print("Testing focus_mode...")
    focus_on_result = session.computer.focus_mode(True)
    assert focus_on_result.success, f"Focus mode on failed: {focus_on_result.error_message}"
    print("Focus mode enabled successfully")
    time.sleep(1)

    focus_off_result = session.computer.focus_mode(False)
    assert focus_off_result.success, f"Focus mode off failed: {focus_off_result.error_message}"
    print("Focus mode disabled successfully")

    # Test MaximizeWindow
    print("Testing maximize_window...")
    maximize_result = session.computer.maximize_window(calculator_window_id)
    assert maximize_result.success, f"Maximize window failed: {maximize_result.error_message}"
    print("Calculator window maximized successfully")
    time.sleep(2)

    # Take screenshot after maximize
    print("Taking screenshot after maximize...")
    screenshot_result = session.computer.screenshot()
    if screenshot_result.success and screenshot_result.data:
        try:
            save_screenshot_from_url(screenshot_result.data, "calculator_maximized.png")
            print("Maximized screenshot saved as calculator_maximized.png")
        except Exception as e:
            print(f"Warning: Failed to save maximized screenshot: {e}")
    else:
        print(f"Screenshot failed or returned empty data: {screenshot_result.error_message}")

    # Test MinimizeWindow
    print("Testing minimize_window...")
    minimize_result = session.computer.minimize_window(calculator_window_id)
    assert minimize_result.success, f"Minimize window failed: {minimize_result.error_message}"
    print("Calculator window minimized successfully")
    time.sleep(2)

    # Take screenshot after minimize
    print("Taking screenshot after minimize...")
    screenshot_result = session.computer.screenshot()
    if screenshot_result.success and screenshot_result.data:
        try:
            save_screenshot_from_url(screenshot_result.data, "calculator_minimized.png")
            print("Minimized screenshot saved as calculator_minimized.png")
        except Exception as e:
            print(f"Warning: Failed to save minimized screenshot: {e}")
    else:
        print(f"Screenshot failed or returned empty data: {screenshot_result.error_message}")

    # Test RestoreWindow
    print("Testing restore_window...")
    restore_result = session.computer.restore_window(calculator_window_id)
    assert restore_result.success, f"Restore window failed: {restore_result.error_message}"
    print("Calculator window restored successfully")
    time.sleep(2)

    # Take screenshot after restore
    print("Taking screenshot after restore...")
    screenshot_result = session.computer.screenshot()
    if screenshot_result.success and screenshot_result.data:
        try:
            save_screenshot_from_url(screenshot_result.data, "calculator_restored.png")
            print("Restored screenshot saved as calculator_restored.png")
        except Exception as e:
            print(f"Warning: Failed to save restored screenshot: {e}")
    else:
        print(f"Screenshot failed or returned empty data: {screenshot_result.error_message}")

    # Test ResizeWindow
    print("Testing resize_window...")
    resize_result = session.computer.resize_window(calculator_window_id, 600, 400)
    assert resize_result.success, f"Resize window failed: {resize_result.error_message}"
    print("Calculator window resized to 600x400 successfully")
    time.sleep(2)

    # Take screenshot after resize
    print("Taking screenshot after resize...")
    screenshot_result = session.computer.screenshot()
    if screenshot_result.success and screenshot_result.data:
        try:
            save_screenshot_from_url(screenshot_result.data, "calculator_resized.png")
            print("Resized screenshot saved as calculator_resized.png")
        except Exception as e:
            print(f"Warning: Failed to save resized screenshot: {e}")
    else:
        print(f"Screenshot failed or returned empty data: {screenshot_result.error_message}")

    # Test FullscreenWindow
    print("Testing fullscreen_window...")
    fullscreen_result = session.computer.fullscreen_window(calculator_window_id)
    assert fullscreen_result.success, f"Fullscreen window failed: {fullscreen_result.error_message}"
    print("Calculator window set to fullscreen successfully")
    time.sleep(2)

    # Take screenshot after fullscreen
    print("Taking screenshot after fullscreen...")
    screenshot_result = session.computer.screenshot()
    if screenshot_result.success and screenshot_result.data:
        try:
            save_screenshot_from_url(screenshot_result.data, "calculator_fullscreen.png")
            print("Fullscreen screenshot saved as calculator_fullscreen.png")
        except Exception as e:
            print(f"Warning: Failed to save fullscreen screenshot: {e}")
    else:
        print(f"Screenshot failed or returned empty data: {screenshot_result.error_message}")

    # Cleanup - CloseWindow
    print("Cleaning up: Closing Calculator window...")
    close_result = session.computer.close_window(calculator_window_id)
    if close_result.success:
        print("Calculator window closed successfully")
    else:
        print(f"Warning: Failed to close Calculator window: {close_result.error_message}")
