import time
# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

# ci-stable
from uuid import uuid4

import pytest

from agentbay import ContextSync
from agentbay import CreateSessionParams


@pytest.mark.sync
def test_session_delete_without_params(agent_bay_client):
    """Test session deletion without parameters, then verify via list."""
    print("Creating session for parameter-less deletion test...")
    result = agent_bay_client.create()
    assert result.success
    assert result.session is not None
    session = result.session
    print(f"Session created successfully, ID: {session.session_id}")

    print("Deleting session using parameter-less delete method...")
    delete_result = session.delete()
    assert delete_result.success
    print(f"Session deleted successfully (RequestID: {delete_result.request_id})")

    time.sleep(2)

    list_result = agent_bay_client.list()
    assert list_result.success
    assert session.session_id not in list_result.session_ids, \
        f"Session ID {session.session_id} still exists after deletion"


@pytest.mark.sync
def test_session_delete_with_sync_context_and_verify(agent_bay_client):
    """Test session deletion with sync_context=True, with context creation and cleanup."""
    context_name = f"test-context-{uuid4().hex[:8]}"
    print(f"Creating context: {context_name}...")
    context_result = agent_bay_client.context.get(context_name, create=True)
    assert context_result.success
    assert context_result.context is not None
    context = context_result.context
    print(f"Context created successfully, ID: {context.id}")

    persistence_data = [
        ContextSync(context_id=context.id, path="/home/wuying/test")
    ]
    params = CreateSessionParams(
        image_id="linux_latest", context_syncs=persistence_data
    )

    print("Creating session with context...")
    result = agent_bay_client.create(params)
    assert result.success
    assert result.session is not None
    session = result.session
    print(f"Session created successfully, ID: {session.session_id}")

    print("Deleting session using sync_context=True...")
    delete_result = session.delete(sync_context=True)
    assert delete_result.success
    print(f"Session deleted successfully (RequestID: {delete_result.request_id})")

    time.sleep(2)
    list_result = agent_bay_client.list()
    assert list_result.success
    assert session.session_id not in list_result.session_ids

    try:
        context_delete_result = agent_bay_client.context.delete(context)
        if context_delete_result.success:
            print(f"Context {context.id} deleted successfully")
    except Exception as e:
        print(f"Warning: Failed to delete context {context.id}: {e}")


@pytest.mark.sync
def test_delete_multiple_sessions(agent_bay_client):
    """Test deleting multiple sessions sequentially."""
    sessions = []
    for i in range(3):
        result = agent_bay_client.create()
        assert result.success is True
        sessions.append(result.session)

    for session in sessions:
        delete_result = agent_bay_client.delete(session)
        assert delete_result.success is True
        print(f"Session {session.session_id} deleted")

    print(f"Deleted {len(sessions)} sessions")
