# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for beta pause and beta resume operations (pytest style).
ci-stable
"""

from uuid import uuid4

import pytest
import pytest

from agentbay import AgentBay, CreateSessionParams


def _create_test_session(agent_bay: AgentBay) -> object:
    session_name = f"test-beta-pause-resume-{uuid4().hex[:8]}"
    params = CreateSessionParams(
        image_id="linux_latest",
        labels={"project": "piaoyun-demo", "environment": "testing", "name": session_name},
    )
    result = agent_bay.create(params)
    assert result.success, f"Failed to create session: {result.error_message}"
    assert result.session is not None, "Session object is None"
    return result.session


def _safe_cleanup_session(agent_bay: AgentBay, session) -> None:
    if session is None:
        return

    try:
        status_result = session.get_status()
        if (status_result.success and status_result.status == "FINISH"):
            print(f"Session {session.session_id} is already finished, skipping cleanup.")
            return
        if status_result.success and status_result.status == "PAUSED":
            session.beta_resume(timeout=180, poll_interval=3)
    except Exception:
        pass

    try:
        agent_bay.delete(session)
    except Exception:
        pass


@pytest.fixture
def session(agent_bay_client: AgentBay):
    s = _create_test_session(agent_bay_client)
    try:
        yield s
    finally:
        _safe_cleanup_session(agent_bay_client, s)


@pytest.mark.sync
def test_beta_pause_and_resume_session_success(session) -> None:
    status_result = session.get_status()
    assert status_result.success, f"Failed to get session status: {status_result.error_message}"
    assert status_result.status == "RUNNING", f"Expected RUNNING, got {status_result.status}"

    pause_result = session.beta_pause(timeout=600, poll_interval=2.0)
    assert pause_result.success, f"beta_pause failed: {pause_result.error_message}"
    assert pause_result.status == "PAUSED", f"Expected PAUSED, got {pause_result.status}"

    resume_result = session.beta_resume(timeout=600, poll_interval=2.0)
    assert resume_result.success, f"beta_resume failed: {resume_result.error_message}"
    assert resume_result.status == "RUNNING", f"Expected RUNNING, got {resume_result.status}"


@pytest.mark.sync
def test_beta_pause_and_delete_session_success(agent_bay_client: AgentBay):
    agent_bay = agent_bay_client
    s = _create_test_session(agent_bay)
    try:
        pause_result = s.beta_pause(timeout=600, poll_interval=2.0)
        assert pause_result.success, f"beta_pause failed: {pause_result.error_message}"

        resume_result = s.beta_resume(timeout=600, poll_interval=2.0)
        assert resume_result.success, f"beta_resume failed: {resume_result.error_message}"

        delete_result = agent_bay.delete(s)
        assert delete_result.success, f"delete failed: {delete_result.error_message}"
    finally:
        _safe_cleanup_session(agent_bay, s)


@pytest.mark.sync
def test_beta_pause_nonexistent_session(agent_bay_client: AgentBay):
    agent_bay = agent_bay_client
    fake_session_id = f"session-nonexistent-{uuid4().hex[:8]}"
    get_result = agent_bay.get(fake_session_id)
    assert not get_result.success, f"Expected get() to fail for nonexistent session {get_result.error_message}"
