# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for skills functionality.
ci-stable

This test calls the real backend without mocks.
"""

import pytest

from agentbay import AgentBay
from agentbay._common.params.session_params import CreateSessionParams


@pytest.mark.sync
def test_get_metadata_returns_skills_root_path(agent_bay_client: AgentBay):
    """get_metadata() should return SkillsMetadataResult with skills_root_path."""
    result = agent_bay_client.beta_skills.get_metadata()

    assert result is not None
    assert isinstance(result.skills_root_path, str)
    assert len(result.skills_root_path) > 0, "skills_root_path should not be empty"
    assert isinstance(result.skills, list)


@pytest.mark.sync
def test_get_metadata_with_skill_names(agent_bay_client: AgentBay):
    """get_metadata(skill_names=[...]) should not raise errors."""
    result = agent_bay_client.beta_skills.get_metadata(skill_names=["non-existent-skill"])
    assert result is not None
    assert isinstance(result.skills, list)
    assert isinstance(result.skills_root_path, str)


@pytest.mark.sync
def test_get_metadata_with_image_id(agent_bay_client: AgentBay):
    """get_metadata(image_id=...) should return skills_root_path for that image."""
    result = agent_bay_client.beta_skills.get_metadata(image_id="linux_latest")
    assert result is not None
    assert isinstance(result.skills_root_path, str)
    assert len(result.skills_root_path) > 0


@pytest.mark.sync
def test_create_session_with_load_skills(agent_bay_client: AgentBay):
    """Creating session with load_skills=True should succeed (backend accepts the param)."""
    params = CreateSessionParams(load_skills=True)
    result = agent_bay_client.create(params)
    assert result.success, f"Session creation failed: {result.error_message}"
    assert result.session is not None
    result.session.delete()

