# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

# ci-stable
import pytest

from agentbay import (
    AgentBay,
    BWList,
    ContextSync,
    CreateSessionParams,
    SyncPolicy,
    WhiteList,
)


@pytest.fixture
def test_context(agent_bay_client: AgentBay):
    context_result = agent_bay_client.context.get("test-wildcard-validation", create=True)
    assert context_result.success
    yield context_result.context
    agent_bay_client.context.delete(context_result.context)


@pytest.mark.sync
def test_create_session_with_wildcard_in_path_should_fail(
    agent_bay_client: AgentBay, test_context
):
    with pytest.raises(ValueError) as exc_info:
        policy = SyncPolicy(bw_list=BWList(white_lists=[WhiteList(path="*.json")]))
        context_sync = ContextSync.new(test_context.id, "/tmp/data", policy)
        agent_bay_client.create(CreateSessionParams(context_syncs=[context_sync]))

    assert "Wildcard patterns are not supported in path" in str(exc_info.value)
    assert "*.json" in str(exc_info.value)


@pytest.mark.sync
def test_create_session_with_wildcard_in_exclude_paths_should_fail(
    agent_bay_client: AgentBay, test_context
):
    with pytest.raises(ValueError) as exc_info:
        policy = SyncPolicy(
            bw_list=BWList(
                white_lists=[WhiteList(path="/src", exclude_paths=["*.log"])]
            )
        )
        context_sync = ContextSync.new(test_context.id, "/tmp/data", policy)
        agent_bay_client.create(CreateSessionParams(context_syncs=[context_sync]))

    assert "Wildcard patterns are not supported in exclude_paths" in str(exc_info.value)
    assert "*.log" in str(exc_info.value)


@pytest.mark.sync
def test_create_session_with_glob_pattern_should_fail(
    agent_bay_client: AgentBay, test_context
):
    with pytest.raises(ValueError) as exc_info:
        policy = SyncPolicy(bw_list=BWList(white_lists=[WhiteList(path="/data/*")]))
        context_sync = ContextSync.new(test_context.id, "/tmp/data", policy)
        agent_bay_client.create(CreateSessionParams(context_syncs=[context_sync]))

    assert "Wildcard patterns are not supported in path" in str(exc_info.value)
    assert "/data/*" in str(exc_info.value)


@pytest.mark.sync
def test_create_session_with_double_asterisk_should_fail(
    agent_bay_client: AgentBay, test_context
):
    with pytest.raises(ValueError) as exc_info:
        policy = SyncPolicy(
            bw_list=BWList(white_lists=[WhiteList(path="/logs/**/*.txt")])
        )
        context_sync = ContextSync.new(test_context.id, "/tmp/data", policy)
        agent_bay_client.create(CreateSessionParams(context_syncs=[context_sync]))

    assert "Wildcard patterns are not supported in path" in str(exc_info.value)


@pytest.mark.sync
def test_create_session_with_valid_paths_should_succeed(
    agent_bay_client: AgentBay, test_context
):
    policy = SyncPolicy(
        bw_list=BWList(
            white_lists=[
                WhiteList(path="/src", exclude_paths=["/node_modules", "/temp"])
            ]
        )
    )
    context_sync = ContextSync.new(test_context.id, "/tmp/data", policy)
    session_result = agent_bay_client.create(
        CreateSessionParams(context_syncs=[context_sync])
    )

    try:
        assert session_result.success
        assert session_result.session is not None
    finally:
        if session_result.session is not None:
            agent_bay_client.delete(session_result.session)


@pytest.mark.sync
def test_validation_happens_before_api_call(
    agent_bay_client: AgentBay, test_context
):
    with pytest.raises(ValueError) as exc_info:
        policy = SyncPolicy(bw_list=BWList(white_lists=[WhiteList(path="*.txt")]))
        ContextSync.new(test_context.id, "/tmp/data", policy)

    assert "Wildcard patterns are not supported in path" in str(exc_info.value)
