# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for context updates.
ci-stable
"""

import pytest


@pytest.mark.sync
def test_context_file_update(agent_bay_client):
    """Test updating file in context using upload URLs."""
    import httpx

    ctx_result = agent_bay_client.context.get("update_ctx", create=True)
    assert ctx_result.success

    try:
        upload_url_result = agent_bay_client.context.get_file_upload_url(
            ctx_result.context_id, "/update_file.txt"
        )
        assert upload_url_result.success

        original_content = b"original content"
        with httpx.Client() as client:
            response = client.put(upload_url_result.url, content=original_content)
            assert response.status_code == 200

        upload_url_result2 = agent_bay_client.context.get_file_upload_url(
            ctx_result.context_id, "/update_file.txt"
        )
        assert upload_url_result2.success

        updated_content = b"updated content"
        with httpx.Client() as client:
            response = client.put(upload_url_result2.url, content=updated_content)
            assert response.status_code == 200

        download_url_result = agent_bay_client.context.get_file_download_url(
            ctx_result.context_id, "/update_file.txt"
        )
        assert download_url_result.success

        with httpx.Client() as client:
            response = client.get(download_url_result.url)
            assert response.status_code == 200
            assert response.content == updated_content

        print("Context file updated successfully")
    finally:
        agent_bay_client.context.delete(ctx_result.context)
