# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

# ci-stable
"""Integration tests for network bind token API."""

import pytest

from agentbay import AgentBay


@pytest.mark.sync
def test_network_create_describe_and_bind_session(agent_bay_client: AgentBay):
    net_result = agent_bay_client.beta_network.get_network_bind_token()
    assert net_result.success, net_result.error_message
    assert net_result.network_id != ""
    assert net_result.network_token != ""
