// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aliyun/wuying-agentbay-sdk/golang/pkg/agentbay/interface (interfaces: GitInterface)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	git "github.com/aliyun/wuying-agentbay-sdk/golang/pkg/agentbay/git"
	gomock "github.com/golang/mock/gomock"
)

// MockGitInterface is a mock of GitInterface interface.
type MockGitInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitInterfaceMockRecorder
}

// MockGitInterfaceMockRecorder is the mock recorder for MockGitInterface.
type MockGitInterfaceMockRecorder struct {
	mock *MockGitInterface
}

// NewMockGitInterface creates a new mock instance.
func NewMockGitInterface(ctrl *gomock.Controller) *MockGitInterface {
	mock := &MockGitInterface{ctrl: ctrl}
	mock.recorder = &MockGitInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitInterface) EXPECT() *MockGitInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockGitInterface) Add(arg0 string, arg1 ...git.AddOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockGitInterfaceMockRecorder) Add(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockGitInterface)(nil).Add), varargs...)
}

// CheckoutBranch mocks base method.
func (m *MockGitInterface) CheckoutBranch(arg0, arg1 string, arg2 ...git.CheckoutOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckoutBranch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockGitInterfaceMockRecorder) CheckoutBranch(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBranch", reflect.TypeOf((*MockGitInterface)(nil).CheckoutBranch), varargs...)
}

// Clone mocks base method.
func (m *MockGitInterface) Clone(arg0 string, arg1 ...git.CloneOption) (*git.GitCloneResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Clone", varargs...)
	ret0, _ := ret[0].(*git.GitCloneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone.
func (mr *MockGitInterfaceMockRecorder) Clone(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockGitInterface)(nil).Clone), varargs...)
}

// Commit mocks base method.
func (m *MockGitInterface) Commit(arg0, arg1 string, arg2 ...git.CommitOption) (*git.GitCommitResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Commit", varargs...)
	ret0, _ := ret[0].(*git.GitCommitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockGitInterfaceMockRecorder) Commit(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockGitInterface)(nil).Commit), varargs...)
}

// ConfigureUser mocks base method.
func (m *MockGitInterface) ConfigureUser(arg0, arg1, arg2 string, arg3 ...git.ConfigOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConfigureUser", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureUser indicates an expected call of ConfigureUser.
func (mr *MockGitInterfaceMockRecorder) ConfigureUser(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureUser", reflect.TypeOf((*MockGitInterface)(nil).ConfigureUser), varargs...)
}

// CreateBranch mocks base method.
func (m *MockGitInterface) CreateBranch(arg0, arg1 string, arg2 ...git.BranchCreateOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBranch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranch indicates an expected call of CreateBranch.
func (mr *MockGitInterfaceMockRecorder) CreateBranch(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockGitInterface)(nil).CreateBranch), varargs...)
}

// DeleteBranch mocks base method.
func (m *MockGitInterface) DeleteBranch(arg0, arg1 string, arg2 ...git.BranchDeleteOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBranch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranch indicates an expected call of DeleteBranch.
func (mr *MockGitInterfaceMockRecorder) DeleteBranch(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranch", reflect.TypeOf((*MockGitInterface)(nil).DeleteBranch), varargs...)
}

// GetConfig mocks base method.
func (m *MockGitInterface) GetConfig(arg0, arg1 string, arg2 ...git.ConfigOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConfig", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockGitInterfaceMockRecorder) GetConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockGitInterface)(nil).GetConfig), varargs...)
}

// Init mocks base method.
func (m *MockGitInterface) Init(arg0 string, arg1 ...git.InitOption) (*git.GitInitResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Init", varargs...)
	ret0, _ := ret[0].(*git.GitInitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Init indicates an expected call of Init.
func (mr *MockGitInterfaceMockRecorder) Init(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockGitInterface)(nil).Init), varargs...)
}

// ListBranches mocks base method.
func (m *MockGitInterface) ListBranches(arg0 string, arg1 ...git.BranchListOption) (*git.GitBranchListResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBranches", varargs...)
	ret0, _ := ret[0].(*git.GitBranchListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockGitInterfaceMockRecorder) ListBranches(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockGitInterface)(nil).ListBranches), varargs...)
}

// Log mocks base method.
func (m *MockGitInterface) Log(arg0 string, arg1 ...git.LogOption) (*git.GitLogResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Log", varargs...)
	ret0, _ := ret[0].(*git.GitLogResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitInterfaceMockRecorder) Log(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitInterface)(nil).Log), varargs...)
}

// Pull mocks base method.
func (m *MockGitInterface) Pull(arg0 string, arg1 ...git.PullOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Pull", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pull indicates an expected call of Pull.
func (mr *MockGitInterfaceMockRecorder) Pull(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockGitInterface)(nil).Pull), varargs...)
}

// RemoteAdd mocks base method.
func (m *MockGitInterface) RemoteAdd(arg0, arg1, arg2 string, arg3 ...git.RemoteAddOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoteAdd", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoteAdd indicates an expected call of RemoteAdd.
func (mr *MockGitInterfaceMockRecorder) RemoteAdd(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteAdd", reflect.TypeOf((*MockGitInterface)(nil).RemoteAdd), varargs...)
}

// RemoteGet mocks base method.
func (m *MockGitInterface) RemoteGet(arg0, arg1 string, arg2 ...git.RemoteGetOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoteGet", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteGet indicates an expected call of RemoteGet.
func (mr *MockGitInterfaceMockRecorder) RemoteGet(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteGet", reflect.TypeOf((*MockGitInterface)(nil).RemoteGet), varargs...)
}

// Reset mocks base method.
func (m *MockGitInterface) Reset(arg0 string, arg1 ...git.ResetOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reset", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockGitInterfaceMockRecorder) Reset(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockGitInterface)(nil).Reset), varargs...)
}

// Restore mocks base method.
func (m *MockGitInterface) Restore(arg0 string, arg1 []string, arg2 ...git.RestoreOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Restore", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockGitInterfaceMockRecorder) Restore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockGitInterface)(nil).Restore), varargs...)
}

// SetConfig mocks base method.
func (m *MockGitInterface) SetConfig(arg0, arg1, arg2 string, arg3 ...git.ConfigOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetConfig", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockGitInterfaceMockRecorder) SetConfig(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockGitInterface)(nil).SetConfig), varargs...)
}

// Status mocks base method.
func (m *MockGitInterface) Status(arg0 string, arg1 ...git.StatusOption) (*git.GitStatusResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Status", varargs...)
	ret0, _ := ret[0].(*git.GitStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockGitInterfaceMockRecorder) Status(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockGitInterface)(nil).Status), varargs...)
}
